FROM yiisoftware/yii2-php:7.4-apache

RUN apt-get update && apt-get upgrade -y && apt-get install mc -y && apt-get install nano -y  && apt-get install gdal-bin -y  && apt-get install libgdal-dev -y
#CMD ["/app/tests/bin/yii", "serve"]
